Create character-components.mdx
ahoylabs/faraday-guides pull request #22
Opened 2023-11-14 20:25 UTC by pacmanincarnate

Added section back in that explains the components of the character, along with information on what is sent to the model.

I think this will be really helpful for people to understand how to create their own characters.

2023-11-16 20:00 UTC, spencekim commented on src/pages/character-creation/character-components.mdx
> +In Faraday, characters are composed of text split into several fields. Each of these field is explained below.
"each of these fields"

2023-11-16 22:29 UTC, pacmanincarnate commented on src/pages/character-creation/character-components.mdx
> +In Faraday, characters are composed of text split into several fields. Each of these field is explained below.
updated.

2023-11-16 22:40 UTC, pacmanincarnate commented
Incorporated meta file change from #24

2023-11-16 23:28 UTC, pacmanincarnate commented
Revised wording based on Grammerly feedback.

2023-12-21 00:41 UTC, spencekim requested changes
A lot of these are quite long winded. I think we can cut down the language to make it easier to parse.

2023-12-21 00:41 UTC, spencekim commented on src/pages/character-creation/character-components.mdx
> +The name of the character, as seen on the home screen or the Character Hub. It is helpful to make this somewhat descriptive of the character and scenario, rather than just their name. The display nam
can we capitalize all references to "Character"?

2023-12-21 00:41 UTC, spencekim commented on src/pages/character-creation/_meta.json
> +  "character-components": "Character Components"
this is missing a comma at the end of the line, which will break the build

2023-12-21 00:41 UTC, spencekim commented on src/pages/character-creation/character-components.mdx
> +This is the name of the character that will be used within the chat. Messages sent by the AI will be prefixed with "*#character:*", where 'character' is the name you have chosen. When developing your
You can't put `{character}` inside of this markdown file. It will try referencing a variable that does not exist and break.

2023-12-21 00:41 UTC, spencekim commented on src/pages/character-creation/character-components.mdx
> +The name of the character, as seen on the home screen or the Character Hub. It is helpful to make this somewhat descriptive of the character and scenario, rather than just their name. The display nam
incorrect use of semicolon

2023-12-21 00:41 UTC, spencekim commented on src/pages/character-creation/character-components.mdx
> +![Character Creator Personas and Scenario](/images/creator_persona.png)
can we make these images consistent with the others? I can re-take them if needed

2023-12-21 01:10 UTC, pacmanincarnate commented on src/pages/character-creation/character-components.mdx
> +![Character Creator Personas and Scenario](/images/creator_persona.png)
I suggest you make the images. I can’t really match the same format completely.

2023-12-21 06:23 UTC, pacmanincarnate commented on src/pages/character-creation/character-components.mdx
> +The name of the character, as seen on the home screen or the Character Hub. It is helpful to make this somewhat descriptive of the character and scenario, rather than just their name. The display nam
both fixed.

2023-12-21 06:23 UTC, pacmanincarnate commented on src/pages/character-creation/_meta.json
> +  "character-components": "Character Components"
fixed.

2023-12-21 06:24 UTC, pacmanincarnate commented on src/pages/character-creation/character-components.mdx
> +This is the name of the character that will be used within the chat. Messages sent by the AI will be prefixed with "*#character:*", where 'character' is the name you have chosen. When developing your
resolved slightly awkwardly, but not terribly.

2023-12-21 06:25 UTC, pacmanincarnate commented
Check out the latest version.

2024-01-02 06:58 UTC, merged